language: python
sudo: yes
dist: xenial

branches:
  only:
    - master

python:
  - "3.7"  # 3.7 development branch
  
install:
  - pip install octadist

script:
  - cd example-py
  - python example_1.py
  - python example_2.py
  - python example_3.py
  - python example_4.py

