language: python
sudo: yes
dist: xenial

branches:
  only:
    - master

python:
  - "3.7"  # 3.7 development branch
  
install:
  # - pip install octadist
  # - pip install -i https://test.pypi.org/simple/ octadist
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install --index-url https://test.pypi.org/simple/ octadist==2.5.2.2

script:
  - cd example-py
  - python example_1.py
  - python example_2.py
  - python example_3.py
  - python example_4.py
  - python example_5.py
